### ISSUE TITLE
Type TeamCityAPI.Type Conflicts with System.Type

### ISSUE THREAD

**Issue by ilc-ilopez** [ISBronny/TeamCityAPI#2]
Having some issues with auto-generated code, and i'm not able to change how the generator handles the mistmatch between "Type" from the TeamCityAPI namespace and the System namespace.

`'Type' is an ambiguous reference between 'TeamCityAPI.Type' and 'System.Type'`

**Comment by ISBronny** [comment]
Hey! Can you send an example of the code in which the error occurs?

**Comment by ilc-ilopez** [comment]
Yep will do later today.

**Comment by ilc-ilopez** [comment]
Aight, now I cant even reproduce. I'm sure someone later might come across this problem and can reference this issue.
